### ISSUE TITLE
Scrap links

### ISSUE THREAD

**Issue by thecseguy** [thecseguy/thepythoncode#1]
Write a python program to scrap 
all the links from a webpage.

**Comment by hasanmdarif** [comment]
Hey @thecseguy  I want to write code for this. Can you please assign this to me?

**Comment by thecseguy** [comment]
> Hey @thecseguy I want to write code for this. Can you please assign this to me?

Sure, go ahead :+1:

**Comment by thecseguy** [comment]
Any changes in the code will be warmly welcome.
Anyone else interested can go ahead on this issue.

**Comment by grumhub** [comment]
Hasanmdarif has a very elegant solution :) DO we want to put some kind of wrapper round this maybe?

**Comment by ghost** [comment]
Hey thecseguy i recently made a CLI program that can take in the file and find broken links. Check it out here https://github.com/jiyoungsin/OSD_A1_Tool I am sure that we can tweak it a little so that It can take urls too. please let me know if this would be beneficial.

**Comment by thecseguy** [comment]
> Hey thecseguy i recently made a CLI program that can take in the file and find broken links. Check it out here https://github.com/jiyoungsin/OSD_A1_Tool I am sure that we can tweak it a little so that It can take urls too. please let me know if this would be beneficial.

This is good buddy 👍

**Comment by thecseguy** [comment]
> Hasanmdarif has a very elegant solution :) DO we want to put some kind of wrapper round this maybe?

Sure, go ahead. Make a pr when you are done
