### ISSUE TITLE
Algorithms and data structure

### ISSUE THREAD

**Issue by thecseguy** [thecseguy/thepythoncode#6]
Write python code for various algo and data structure.

**Comment by pbuggaveeti28** [comment]
Can I contribute?

**Comment by suraj111999** [comment]
Can you please assign this issue to me?

**Comment by gaurangisinha** [comment]
Hello, @thecseguy Could you please assign this issue to me, I will be very grateful.

**Comment by thecseguy** [comment]
@gaurangisinha @padmaja-22 @suraj111999 @sattyamjjain 
Please write your code and make a pull request. I'll try to merge

**Comment by shubham2704** [comment]
@thecseguy i would like to work on this issue

**Comment by Divyessh** [comment]
Sir Can I contribute here?

**Comment by Hinal-Srivastava** [comment]
Hey!
I can add interpolation search and exponential search.

**Comment by thecseguy** [comment]
@Hinal-Srivastava @shubham2704 
Go ahead :)

**Comment by adarshcode** [comment]
@thecseguy can i contribute?

**Comment by thecseguy** [comment]
> @thecseguy can i contribute?

Sure

**Comment by kkkkkabir** [comment]
Hey! Can you assign this to me?

**Comment by thecseguy** [comment]
> Hey! Can you assign this to me?

@kkkkkabir  Make a pull request when you're done
